"""empty message

Revision ID: 764cca405873
Revises: a14d9eac660e
Create Date: 2025-01-15 12:44:00.366363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '764cca405873'
down_revision: Union[str, None] = 'a14d9eac660e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aplications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aplications_id'), 'aplications', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aplications_id'), table_name='aplications')
    op.drop_table('aplications')
    # ### end Alembic commands ###
